### PR TITLE
Document on article redirect/jump

### LINKED ISSUE #53: Add article to document redirect feature
https://github.com/Pelican-Elegant/elegant/pull/244

### PR DESCRIPTION
**Pull request by iranzo**
Closes #53

### CODE REVIEW

**Comment by iranzo** [comment]
@talha131 

It will report the test as failed, since this one is merged as it will fail html validation until all templates are fixed, please do merge manually

**Comment by talha131** [comment]
Blocked by https://github.com/Pelican-Elegant/elegant/pull/244#issuecomment-450868718

**Comment by iranzo** [comment]
Updated doc to match https://github.com/Pelican-Elegant/elegant/pull/252

**Comment by talha131** [comment]
@AWegnerGitHub thank for you reviewing it.

**Pull request merged**
