### PR TITLE
Add documentation on how to utilize the author blurb feature

### PR DESCRIPTION
**Pull request by AWegnerGitHub**
Provides an overview of the AUTHORS dictionary, an explaination on
different metatags on when to use them and how it impacts the
appearance of author information, and a screenshot of how this will
look with multiple authors.

Should be merged only after https://github.com/Pelican-Elegant/elegant/pull/195 is merged

### CODE REVIEW

**Comment by talha131** [comment]
Thanks for contributing. I highly recommend putting this information in a separate article, instead of appending it to misc-features.

This is an important feature that you contributed. We must make it visible.

**Comment by AWegnerGitHub** [comment]
Thanks @talha131 . I've pulled that information out into it's own article.

**Comment by talha131** [comment]
@AWegnerGitHub do you mind if you squash the commits? The first commit is merely noise now.

**Comment by AWegnerGitHub** [comment]
Sure. That is fine with me. I will do that next time. Thank you.

**Pull request merged**
