### PR TITLE
Initial contribute document

### LINKED ISSUE #34: Add page to encourage visitors to contribute
1. Add a page
1. Show it in the top menu bar

Content needs to be about

1. Please contribute, even if a little
1. If you can't code then help in documentation
1. Please, please contribute.
1. Please, please contribute.
1. Please, please contribute.

You get the idea.

### PR DESCRIPTION
**Pull request by iranzo**
Feedback welcome

#Closes #34

-----
[View rendered content/Development/contribute.md](https://github.com/iranzo/documentation/blob/contribute/content/Development/contribute.md)

### CODE REVIEW

**Comment by talha131** [comment]
Shouldn't we add content from contributing document to it?

Secondly, we will end up with two files, first in the elegant repo and second in here. We will have to make sure both files are in always in sync. I wonder if it is worth it.

To be clear I am not for or against this PR at the moment.

**Comment by iranzo** [comment]
Usually, for people willing to contribute there's the CONTRIBUTING file in the repos, so probably is not needed, whoever is willing to code or to contrib is aware (IMHO).

in order to avoid mantaining both, I would link uri of final document in 'documentation' repo from 'CONTRIBUTING' in 'theme' repo

**Comment by talha131** [comment]
One advantage of this PR is that we can link to it in release notes or in a ubiquitous banner on the docs site. So this PR is not completely without merit.

**Comment by iranzo** [comment]
I'm lost :-) what should be the plan forward?

**Comment by silverhook** [comment]
I think a link to the `CONTRIBUTING.md` file in the `elegant` repo would be a good idea in the sense of 

> For more details how to set up your environment and how to write code for Elegant, see `CONTRIBUTING.md`.

Otherwise it looks OK at this stage. We’re still a small community, so not worth over-doing it :)

Eventually it would make sense to have a longer article that is more aimed at low-barrier contributions to explains step-by-step how to go about it.

**Comment by iranzo** [comment]
Added :-)

**Comment by silverhook** [comment]
LGTM.

**Comment by iranzo** [comment]
image

**Comment by iranzo** [comment]
@talha131 anything missing from your side?

**Comment by talha131** [comment]
@iranzo Will get back to you.

**Comment by talha131** [comment]
Close via https://github.com/Pelican-Elegant/elegant/pull/345

**Pull request closed without merging**
